GET http://localhost:3000/api/estadisticas

###

GET http://localhost:3000/api/estadisticas/4 

###

POST  http://localhost:3000/api/estadisticas 
Content-Type: application/json

{

"Lpm": 102,
"temperatura": "38°C",
"ubicacion": "40? 24' 59'' N; 03? 42' 09'' O",
"IdPet": 729

}

###

DELETE http://localhost:3000/api/estadisticas/7